export const EVENT_FOCUS = 'onFocus'
export const EVENT_BLUR = 'onBlur'
export const EVENT_CHANGE = 'onChange'
export const EVENT_KEYDOWN = 'onKeydown'
export const EVENT_KEYUP = 'onKeyup'
export const EVENT_VALUE_CHANGE = 'onValueChange'
export const EVENT_COMPOSITION_START = "onCompositionStart"
export const EVENT_COMPOSITION_END = "onCompositionEnd"
export const EVENT_SELECTION_CHANGE = 'onSelectionChange'
export const EVENT_SELECT_START = 'onSelectStart'
export const EVENT_SELECTING = 'onSelecting'
export const EVENT_SELECT_END = 'onSelectEnd'
export const EVENT_NODE_UPDATE = 'onNodeUpdate'
export const EVENT_DOM_RENDER = 'onDomRender'
export const EVENT_ROOT_DOM_RENDER = 'onRootDomRender'

export const DATA_KEY = 'data-editable-key'
export const DATA_TYPE = 'data-type'
export const DATA_TYPE_TEXT = 'text'
export const DATA_TYPE_ELEMENT = 'element'

export const OP_UPDATE_DATA = 'updateData'
export const OP_UPDATE_FORMAT = 'updateFormat'
export const OP_UPDATE_STYLE = 'updateStyle'
export const OP_INSERT_TEXT = 'insertText'
export const OP_DELETE_TEXT = 'deleteText'
export const OP_INSERT_NODE = 'insertNode'
export const OP_DELETE_NODE = 'deleteNode'