export const DATA_EDITOR_KEY = 'data-editor-key'
export const DATA_KEY = 'data-editable-key'
export const DATA_TYPE = 'data-type'
export const DATA_TYPE_TEXT = 'text'
export const DATA_TYPE_ELEMENT = 'element'

export const OP_UPDATE_DATA = 'update_data'
export const OP_UPDATE_FORMAT = 'update_format'
export const OP_UPDATE_STYLE = 'update_style'
export const OP_INSERT_TEXT = 'insert_text'
export const OP_DELETE_TEXT = 'delete_text'
export const OP_INSERT_NODE = 'insert_node'
export const OP_DELETE_NODE = 'delete_node'