export const EVENT_FOCUS = 'onFocus'
export const EVENT_BLUR = 'onBlur'
export const EVENT_CHANGE = 'onChange'
export const EVENT_KEYDOWN = 'onKeydown'
export const EVENT_KEYUP = 'onKeyup'
export const EVENT_VALUE_CHANGE = 'onValueChange'
export const EVENT_SELECTION_CHANGE = 'onSelectionChange'
export const EVENT_SELECT_START = 'onSelectStart'
export const EVENT_SELECTING = 'onSelecting'
export const EVENT_SELECT_END = 'onSelectEnd'
export const EVENT_NODE_UPDATE = 'onNodeUpdate'
export const EVENT_NODE_DID_UPDATE = 'onNodeDidUpdate'

export const DATA_KEY = 'data-key'
export const DATA_ELEMENT_TYPE = 'data-editable-type'